### ISSUE TITLE
Can't save image through image_view on Kinetic

### ISSUE THREAD

**Issue by wangji1** [ros-perception/image_pipeline#235]
On kinetic, when use mouse to right click image_view screen, it was failed to save the image.
And also image_view screen will be hang, even can't terminate it by press ctrl+c on terminal

**Comment by k-okada** [comment]
is this same issue?? ->
https://github.com/ros-perception/image_pipeline/pull/184

## 

◉ Kei Okada

2016-11-11 14:52 GMT+09:00 Jinliang Wang notifications@github.com:

**Comment by wangji1** [comment]
similar...

Is that issue fixed?
but I have always upgraded ROS packages, so I think my used tool version should be latest, still has the problem.

If should I remove opencv, and try again?

**Comment by k-okada** [comment]
which version of image_pipeline are you using, try rosversion image_view

## 

◉ Kei Okada

2016-11-15 10:09 GMT+09:00 Jinliang Wang notifications@github.com:

**Comment by wangji1** [comment]
$ rosversion image_view
1.12.19

**Comment by wangji1** [comment]
![image_view_hang](https://cloud.githubusercontent.com/assets/18045157/20373076/9db6ae04-acaa-11e6-8efb-ec0e3eb81254.png)
This shows the image_view screen is hang

**Comment by wangji1** [comment]
![image_view_running](https://cloud.githubusercontent.com/assets/18045157/20373104/c9e4cd26-acaa-11e6-863c-9abb86772b31.png)
On terminal, there's no information for saved image

**Comment by k-okada** [comment]
humm, it seems @iKrishneel 's fix has been merged at 1.12.16 so may be
different situation.
https://github.com/ros-perception/image_pipeline/blob/indigo/image_view/CHANGELOG.rst

## 

◉ Kei Okada

2016-11-17 10:47 GMT+09:00 Jinliang Wang notifications@github.com:

**Comment by iKrishneel** [comment]
@wangji1  
Did you build opencv from source?  That problems is likely result of OpenGL support. 

I fixed that by rebuilding OCV3 with this flag off: 
`-D WITH_OPENGL=OFF`

saved image with right click
![frame0001](https://cloud.githubusercontent.com/assets/9315167/20381019/cc5b57d0-ace8-11e6-861a-b88547f5686b.jpg)

**Comment by k-okada** [comment]
i think he's install them from deb, @Krishneel can you check if this
happens to your environment too?

## 

◉ Kei Okada

2016-11-17 17:10 GMT+09:00 Krishneel notifications@github.com:

**Comment by wangji1** [comment]
Oh, I did download opencv source and build.

**Comment by k-okada** [comment]
see #236 for the solution.

**Comment by pbeeson** [comment]
I still see this behavior using the current kinetic .deb files.

**Comment by k-okada** [comment]
may be that's because
https://github.com/ros-perception/image_pipeline/pull/236 is not merged and
released yet.

--
◉ Kei Okada


2017-05-16 23:43 GMT+09:00 Patrick Beeson <notifications@github.com>:

**Comment by JWhitleyWork** [comment]
@pbeeson - I know this is a very stale issue but are you still seeing this behavior? @k-okada - Same question.

**Comment by SteveMacenski** [comment]
Closing from non-responsive for 6 months. Feel free to re-open if still a problem in Melodic
